Data wrangling

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
newdf=pd.read_csv("Flickrs-Switzerland-1990-2017.csv")

Extract year from datetaken and plot distribution per year

In [4]:
newdf['year']=newdf['datetaken'].map(lambda x: x[:4])

In [5]:
plt.hist(newdf.year.astype(int),bins=np.arange(1990,2018,1))
plt.show()

We see that it is meaningful to observe only trends from 2005 to 2016 (inclusive) as most of data comes from there. We plot a closer look

In [6]:
plt.hist(newdf.year.astype(int),bins=np.arange(2005,2018,1))
plt.show()

Get data only for the mentioned time period, extract months. We round latitude and longitude to 3 digits.

In [7]:
years_11=newdf[newdf['year'].astype(str).isin(["2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016"])]

In [8]:
years_11['month']=newdf['datetaken'].map(lambda x: x[5:7])

/home/nevena/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [9]:
rounded_geo=years_11
rounded_geo['lat']=round(years_11['lat'].astype(float),3)
rounded_geo['lon']=round(years_11['lon'].astype(float),3)

/home/nevena/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/home/nevena/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

# Popular place per number of pictures

In [10]:
famous_place_per_year=rounded_geo.groupby(["year","lat","lon"]).count()

In [11]:
def findmax(df_in):
    df=df_in.reset_index()
    years=df_in.index.get_level_values(0).unique()
    maxims=list()
    for x in years:
        max_num=max(df[df['year']==x]['userid'])
        maxims.extend([max_num])
    return maxims

In [12]:
fam_places=famous_place_per_year[(famous_place_per_year.userid.isin(findmax(famous_place_per_year)))]

In [13]:
#we drop duplicates for 2008
fam_places=fam_places.reset_index().drop(fam_places.reset_index().index[[4]])

In [14]:
#display on the map
import folium
from IPython.display import HTML, display
SF_COORDINATES = (46,5)
map_2 = folium.Map(location=[46.85, 8.3], zoom_start=8)
for each in fam_places.reset_index().iterrows():
    folium.CircleMarker(location=[each[1]['lat'],each[1]['lon']], radius=each[1]['userid']*2,
                    popup=str(each[1]['year']), color='#3186cc',
                    fill_color='#C70039').add_to(map_2)
display(map_2)
map_2.save("popular_loc1.html")

In [17]:
#see what those places are.. NAMES
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut, GeocoderServiceError
geolocator = Nominatim()
popular_places=[]
for index, row in fam_places.reset_index().iterrows():
    popular_places.extend([geolocator.reverse([row['lat'], row['lon']])])

In [18]:
def getPlaceNames(popular_places):
    names=[]
    for x in popular_places:
        try:
            names.extend([x.raw['address']['city']])
        except KeyError:
            try:
                names.extend([x.raw['address']['village']])
            except KeyError:
                    try:
                        names.extend([x.raw['address']['suburb']])
                    except KeyError:
                        names.extend([x.raw['address']['town']])
    return names

In [19]:
pop_places=fam_places[['year','lat','lon','userid']]
pop_places['num_photos']=pop_places['userid']
pop_places=pop_places[['year','lat','lon','num_photos']]
pop_places['names']=getPlaceNames(popular_places)
pop_places

/home/nevena/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

    year     lat    lon  num_photos              names
0   2005  46.224  7.903         351        Staldenried
1   2006  47.256  9.109         727       Ebnat-Kappel
2   2007  47.560  7.585        1324              Basel
3   2008  46.693  6.911        4333        Romont (FR)
5   2009  46.693  6.912        3749        Romont (FR)
6   2010  47.459  8.242        1644           Mülligen
7   2011  46.235  6.119        2911  Le Grand-Saconnex
8   2012  46.693  6.911        1723        Romont (FR)
9   2013  46.168  6.119        2551    Plan-les-Ouates
10  2014  46.691  6.910        2361        Romont (FR)
11  2015  47.183  7.742        1636         Bleienbach
12  2016  46.168  6.119        1831    Plan-les-Ouates

We also want to check that it is based on similar number of users

In [20]:
def getNumUsers(x,y,z):
    return rounded_geo[(rounded_geo.lat==x) & (rounded_geo.lon==y) & (rounded_geo.year==z)].groupby("userid").count().shape[0]

In [21]:
pop_places['num_users']=tuple(map(lambda lat,lon,year: getNumUsers(lat,lon,year),pop_places['lat'],pop_places['lon'],pop_places['year']))

In [22]:
pop_places

    year     lat    lon  num_photos              names  num_users
0   2005  46.224  7.903         351        Staldenried          1
1   2006  47.256  9.109         727       Ebnat-Kappel          1
2   2007  47.560  7.585        1324              Basel          2
3   2008  46.693  6.911        4333        Romont (FR)          1
5   2009  46.693  6.912        3749        Romont (FR)          2
6   2010  47.459  8.242        1644           Mülligen          1
7   2011  46.235  6.119        2911  Le Grand-Saconnex         18
8   2012  46.693  6.911        1723        Romont (FR)          2
9   2013  46.168  6.119        2551    Plan-les-Ouates          1
10  2014  46.691  6.910        2361        Romont (FR)          1
11  2015  47.183  7.742        1636         Bleienbach          2
12  2016  46.168  6.119        1831    Plan-les-Ouates          1

In [24]:

def word_count(str):
    counts = dict()
    words = str.split()

    for word in words:
        if word in counts:
            counts[word] += 1
        else:
            counts[word] = 1

    return counts
def tagFreq(dfm,year=0):   
    string='  '.join(dfm.dropna().tags.values)
    dictionary=word_count(string)
    dfWords=pd.DataFrame.from_dict(dictionary,orient='index')
    dfWords=dfWords.reset_index()
    dfWords=dfWords.rename(columns={'index': 'word', 0: 'freq'})
    dfWords=dfWords.sort(['freq'],ascending=False)
    dfWords = dfWords.reset_index()[['word','freq']]
    if year!=0: dfWords['year']=year
    return dfWords

In [25]:
most_pop_place_data.groupby("userid").count()

,title,dateupload,datetaken,views,tags,lat,lon,place_id,woeid,year,month
userid,,,,,,,,,,,
12359290@N04,3095,3095,3095,3095,3092,3095,3095,3095,3095,3095,3095

Romont is the most popular place, but we see that one users made most of these posts.<br> After checking the exact location of these posts (just someones house) we drop this user and reevaluate most popular places

In [26]:
without_bored_user=rounded_geo[rounded_geo.userid!='12359290@N04']
newFamous_plase=without_bored_user.groupby(["year","lat","lon"]).count()
new_places=newFamous_plase[(newFamous_plase.userid.isin(findmax(newFamous_plase)))]

In [16]:
#we drop duplicates for 2008
new_placec=new_places.reset_index().drop(new_places.reset_index().index[[4]])
new_placec

,year,lat,lon,userid,title,dateupload,datetaken,views,tags,place_id,woeid,month
0,2005,46.224,7.903,351,351,351,351,351,351,351,351,351
1,2006,47.256,9.109,727,727,727,727,727,727,727,727,727
2,2007,47.560,7.585,1324,215,1324,1324,1324,1324,1324,1324,1324
3,2008,46.973,7.486,1343,1343,1343,1343,1343,1343,1343,1343,1343
5,2009,46.615,7.045,1901,1901,1901,1901,1901,1899,1901,1901,1901
6,2010,47.459,8.242,1644,1644,1644,1644,1644,0,1644,1644,1644
7,2011,46.235,6.119,2911,2154,2911,2911,2911,2654,2911,2911,2911
8,2012,46.277,6.170,1689,1682,1689,1689,1689,1637,1689,1689,1689
9,2013,46.168,6.119,2551,2551,2551,2551,2551,2506,2551,2551,2551
10,2014,47.113,6.846,2117,2117,2117,2117,2117,2115,2117,2117,2117
11,2015,47.183,7.742,1636,1636,1636,1636,1636,1636,1636,1636,1636
12,2016,46.168,6.119,1831,1831,1831,1831,1831,1831,1831,1831,1831

In [32]:
#and again, we display on the map
map_3 = folium.Map(location=[46.85, 8.3], zoom_start=8)
for each in new_placec.reset_index().iterrows():
    folium.CircleMarker(location=[each[1]['lat'],each[1]['lon']], radius=each[1]['userid']*2,
                    popup=str(each[1]['year']), color='#3186cc',
                    fill_color='#C70039').add_to(map_3)
display(map_3)
map_3.save('pop_location_1.html')

As we saw before, next most popular place is Geneva (for 3 years). Let's find my is it so popular, what are the most popular tags?

In [17]:
new_most_pop_place_data=rounded_geo[((rounded_geo.lat==46.235) & (rounded_geo.lon==6.119)) |
                               ((rounded_geo.lat==46.277) & (rounded_geo.lon==6.170)) |
                               ((rounded_geo.lat==46.168) & (rounded_geo.lon==6.119))]

In [81]:
tagFreq(new_most_pop_place_data)

/home/nevena/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:19: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

                       word  freq
0             planlesouates  7987
1                    geneva  6252
2                  natation  5032
3               switzerland  4951
4                      show  4938
5                     motor  4506
6                    genève  3312
7                       car  3254
8                      auto  3148
9                     salon  2592
10                motorshow  2586
11                 swimming  2536
12                     genf  2379
13                  palexpo  2214
14            meetingmaster  2055
15                 autoshow  1994
16                   master  1961
17                 pressday  1944
18                   suisse  1937
19            international  1920
20                    march  1879
21                       ch  1821
22                     2011  1767
23                  versoix  1647
24    natationplanlesouates  1630
25     meetingstnicolas2015  1630
26                  juniors  1630
27                    canon  1625
28                       5d  1553
29                      eos  1513
...                     ...   ...
2469                 100acr     1
2470                   back     1
2471                miniwrc     1
2472                   111r     1
2473                 kadjar     1
2474                 gt3rsr     1
2475              subaruwrx     1
2476                    crd     1
2477                details     1
2478            sigma1224mm     1
2479                   hemi     1
2480                  100mm     1
2481                   ambi     1
2482            sailingship     1
2483                  hugin     1
2484                     tl     1
2485             motorcycle     1
2486             motorbikes     1
2487                   ciel     1
2488                   aero     1
2489             fibreoptic     1
2490               spoilers     1
2491              lionscity     1
2492             scènedevie     1
2493              fabdesign     1
2494                 gclass     1
2495                    glk     1
2496                  davis     1
2497                  start     1
2498                 bayard     1

[2499 rows x 2 columns]

Based on first 10 tags we see that it is because of the car salon. Let's filter only pictures that contain only tags relevant to the car salon

In [19]:
geneva_salon_data=new_most_pop_place_data[new_most_pop_place_data['tags'].str.contains("auto") |
                                    new_most_pop_place_data['tags'].str.contains("car") |
                                    new_most_pop_place_data['tags'].str.contains("auto") |
                                    new_most_pop_place_data['tags'].str.contains("motor") |
                                    new_most_pop_place_data['tags'].str.contains("show") |
                                    new_most_pop_place_data['tags'].str.contains("motorshow") |
                                    new_most_pop_place_data['tags'].str.contains("autoshow") |
                                    new_most_pop_place_data['tags'].str.contains("salon")]

Discover evolution over time of this event

In [35]:
visitors=geneva_salon_data.groupby(['year','userid']).count().reset_index().groupby("year").count()

In [37]:
visitors

,userid,title,dateupload,datetaken,views,tags,lat,lon,place_id,woeid,month
year,,,,,,,,,,,
2005,3,3,3,3,3,3,3,3,3,3,3
2006,2,2,2,2,2,2,2,2,2,2,2
2007,3,3,3,3,3,3,3,3,3,3,3
2008,5,5,5,5,5,5,5,5,5,5,5
2009,8,8,8,8,8,8,8,8,8,8,8
2010,8,8,8,8,8,8,8,8,8,8,8
2011,14,14,14,14,14,14,14,14,14,14,14
2012,15,15,15,15,15,15,15,15,15,15,15
2013,12,12,12,12,12,12,12,12,12,12,12
2014,7,7,7,7,7,7,7,7,7,7,7
2015,9,9,9,9,9,9,9,9,9,9,9
2016,4,4,4,4,4,4,4,4,4,4,4

In [39]:
visitors['userid'].plot()
plt.show()
plt.savefig("number_pf_visitors_geneva.png")

We see that Geneva auto salon was the most popular in 2012. Let's now check the most popular tag per year in the data that concerns this event in order to discover the most popular cars

In [20]:
def getUrlForTags(tags_,lati=0,long=0,year=0,skip=0):
    from flickrapi import FlickrAPI

    FLICKR_PUBLIC='5b03e0e556fc96c0ac2bb6256889b4de'
    FLICKR_SECRET = 'f73faeda2b4f164e'

    flickr = FlickrAPI(FLICKR_PUBLIC, FLICKR_SECRET, format='parsed-json')
    extras='url_sq,url_t,url_s,url_q,url_m,url_n,url_z,url_c,url_l,url_o'
    if(lati!=0): cats = flickr.photos.search(tags = tags_, per_page=55,lat=lati,lon=long,min_taken_date=str(year)+'-01-01',max_taken_date=str(year)+'-12-31',extras=extras, tag_mode='all')
    else: cats = flickr.photos.search(tags = tags, per_page=55, extras=extras,tag_mode='all')
    photos = cats['photos']
    from pprint import pprint
    #print(photos['photo'])
    if(skip!=0): return  photos['photo']
    else: return photos['photo'][0]['url_m']

In [88]:
tagFreq(geneva_salon_data[geneva_salon_data['year']=='2005'])

/home/nevena/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:19: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

                    word  freq
0                    car    48
1                 geneva    31
2                carshow    30
3              autosalon    29
4            astonmartin    12
5                   auto    12
6         salondauto2005    12
7               maserati     6
8                  dodge     4
9                   mini     4
10                 viper     4
11             sportscar     4
12            conceptcar     3
13                 volvo     3
14             crossfire     3
15                   407     3
16              prologue     3
17               peugeot     3
18              chrysler     3
19                   c70     3
20                 froid     2
21               voiture     2
22                frozen     2
23            automotive     2
24                 hiver     2
25                  bise     2
26              lacléman     2
27                toyota     2
28           lamborghini     2
29                  2005     2
..                   ...   ...
48                   645     1
49                 météo     1
50                veyron     1
51            salondauto     1
52               schweiz     1
53            icecovered     1
54              mercedes     1
55                   eis     1
56                  gt40     1
57              concours     1
58              platanes     1
59  développementdurable     1
60              gallardo     1
61                 night     1
62                   4x4     1
63                   bmw     1
64                digest     1
65          voituregelée     1
66               coopers     1
67                genève     1
68             lemanlake     1
69                suisse     1
70                  quai     1
71         environnement     1
72                    gt     1
73                 glacé     1
74           switzerland     1
75                  wind     1
76             chevrolet     1
77                 photo     1

[78 rows x 2 columns]

We see that the most popular car in 2005 was aston martin

In [89]:
tagFreq(geneva_salon_data[geneva_salon_data['year']=='2006'])

/home/nevena/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:19: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

                     word  freq
0                    show   263
1             switzerland   263
2                  geneva   263
3                   motor   260
4                   nikon   251
5                    auto   244
6                  geneve   244
7               autosalon   244
8              automobile   244
9               motorshow   244
10                   2006   244
11                 europe   244
12               autoshow   244
13                    car   244
14               nikond50   244
15                    d50   244
16                  salon   244
17              prototype   148
18             conceptcar   147
19                concept    29
20                   cars    19
21                spadger    19
22               ridewood    19
23                  jimmy    19
24                  james    19
25                 toyota    18
26                classic    16
27               maserati    12
28                porsche    12
29                ferrari    12
..                    ...   ...
68                 veyron     1
69                    ccx     1
70             rangerover     1
71                    gt3     1
72                  isuzu     1
73               koigsegg     1
74                   wcar     1
75                   111r     1
76                  coupé     1
77                  elise     1
78                   ycar     1
79                 fulvia     1
80                   fiat     1
81                   ucar     1
82                     f1     1
83                   tcar     1
84                   mcar     1
85            fulviacoupè     1
86                 engine     1
87                  miura     1
88  istitutoeuropeodesign     1
89                   rcar     1
90                   icar     1
91                   lada     1
92                   lcar     1
93                   bcar     1
94                  royce     1
95                    911     1
96                  coupè     1
97                  exige     1

[98 rows x 2 columns]

Toyota was popular in 2006

In [90]:
tagFreq(geneva_salon_data[geneva_salon_data['year']=='2007'])

/home/nevena/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:19: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

                      word  freq
0                   geneva   333
1              switzerland   213
2                     show   212
3                    motor   212
4                     77th   208
5                motorshow   208
6            international   207
7                     auto    80
8                    salon    80
9                     2007    80
10                    cars    50
11              doganowska    45
12                   dogan    45
13              doganowski    45
14                  europe    45
15              doganowscy    45
16                   trend     5
17                autoshow     5
18                  geneve     5
19  internationalmotorshow     1

No popular car in 2007

In [93]:
tagFreq(geneva_salon_data[geneva_salon_data['year']=='2008'])[0:50]

/home/nevena/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:19: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

                       word  freq
0                      auto   170
1                      2008   139
2                conceptcar   117
3                       car   109
4                    geneva    96
5                     wheel    94
6                  supercar    92
7                  autoshow    92
8                   fashion    91
9                   atelier    91
10                cardetail    91
11                 dreamcar    91
12                  colours    91
13            78thmotorshow    91
14                   geneve    91
15  ginevrasaloneautoeos40d    91
16                  palexpo    91
17                  ginevra    91
18                supercars    91
19                    light    91
20                  voiture    90
21                   teewee    76
22             salondelauto    76
23                   genève    76
24                autosalon    16
25               exhibition    15
26                      che    15
27                  schweiz    15
28          legrandsaconnex    15
29                       ge    15
30                  fpm1979    12
31                  renault    12
32                   hermes     9
33                  edition     9
34                   veyron     9
35                  bugatti     9
36                   nissan     9
37                   mégane     8
38                       f1     7
39                  ferrari     7
40                       8c     6
41                  citroen     6
42             competizione     6
43                    mazda     5
44               sportwagen     5
45                    sport     5
46                alfaromeo     5
47                       c8     4
48                   pagani     4
49                    zonda     4

We see some renault in 2008

In [95]:
tagFreq(geneva_salon_data[geneva_salon_data['year']=='2009'])[0:50]

/home/nevena/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:19: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

                       word  freq
0                    geneva   145
1               switzerland   135
2                        ch   135
3                salondauto    97
4            genevaautoshow    97
5                      auto    94
6                   voiture    74
7                    geneve    74
8                    teewee    71
9                    genève    42
10    confederationhelvetic    38
11    confedrationhelvetica    38
12                 svizzera    38
13                     genf    38
14                   suisse    38
15    helveticconfederation    38
16  confédérationhélvétique    38
17                  schweiz    38
18   confédérationhelvetica    36
19                     cars    32
20                     2009    31
21                   winter    23
22           transportation    23
23                    messe    23
24                autosalon    23
25                    hiver    23
26                 voitures    23
27              exhibitions    23
28      wwwgenevaclassicsch    15
29                 aviation    15
30                   herbst    15
31                  automne    15
32                 wwwgvach    15
33                     lsgg    15
34                      gva    15
35                     fall    14
36                      bmw    13
37            swissairforce    12
38                    armée    12
39                militaire    12
40                     army    12
41                 military    12
42                     2008    11
43                    avion     9
44                 flugzeug     9
45            genevacarshow     9
46                   avione     9
47                 aircraft     9
48                 airplane     9
49                     audi     8

BMW in 2009

In [97]:
tagFreq(geneva_salon_data[geneva_salon_data['year']=='2010'])[0:50]

/home/nevena/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:19: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

                   word  freq
0                   car   107
1              autoshow    99
2               vehicle    89
3               carshow    87
4               voiture    86
5                geneve    86
6              vehicule    85
7        transportation    85
8   2010genevamotorshow    85
9          genfautoshow    85
10               wheels    85
11           automobile    85
12         salondelauto    85
13               geneva    49
14                 auto    46
15            motorshow    35
16              ginevra    35
17                 cars    32
18                 2010    31
19               salone    27
20               genève    27
21            sportscar    23
22            autosalon    23
23        international    20
24          switzerland    20
25                bartw    19
26                nikon    19
27                motor    19
28                 show    19
29               nikkor    19
30                d300s    19
31           autogespot    18
32           automotive    17
33    bartwillemsteinnl    17
34                sedan    16
35            exoticcar    16
36              berline    14
37        autogespotcom    14
38           conceptcar    12
39                 80th    12
40                  bmw    12
41            alfaromeo    11
42      genevamotorshow    11
43        genevacarshow    11
44              peugeot    11
45      salonediginevra    11
46           automobili    11
47                stand    11
48                white    10
49                coupe    10

Bartwillemsteinnl in 2010

In [100]:
tagFreq(geneva_salon_data[geneva_salon_data['year']=='2011'])[50:80]

/home/nevena/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:19: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

                        word  freq
50                   voiture   130
51                      81st   119
52                   carshow   119
53                   genève   116
54                   porsche    95
55                 beautiful    88
56                    geneve    85
57                  hippique    83
58                   jumping    83
59  professionalphotographer    83
60         canoneos1dmarkiii    83
61                      jump    83
62             interantional    83
63                     rolex    83
64                    cheval    83
65                  hippisme    83
66        equinephotographer    83
67                      chiw    83
68                     arena    83
69          concourshippique    83
70           gillesforestier    83
71                     horse    83
72              creditsuisse    83
73                    famous    83
74                   schweiz    79
75                   ferrari    79
76                 autosalon    79
77                     swiss    79
78                     belle    78
79                      sexy    78

Porsche in 2011

In [102]:
tagFreq(geneva_salon_data[geneva_salon_data['year']=='2012'])[0:50]

/home/nevena/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:19: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

                      word  freq
0                   geneva  1090
1                     2012  1069
2                motorshow  1008
3                    salon   996
4              switzerland   995
5                     genf   982
6                  palexpo   981
7                   suisse   978
8                     auto   978
9                     show   961
10                   motor   960
11                     car   925
12                   canon   914
13                     eos   912
14                      5d   904
15           journéepresse   902
16                    mars   902
17                  photos   902
18     automobilemotorshow   902
19  automobilsalongenf2012   902
20         genferautosalon   902
21                autoshow   902
22                   march   902
23                pressday   902
24     genevamotorshow2012   902
25  genevacarshowpressdays   902
26               beautiful   450
27              mostviewed   445
28                    face   445
29                beauties   445
30                   mujer   445
31                  beauty   445
32                 hotesse   445
33                     hot   445
34                    girl   445
35                   woman   445
36               mannequin   445
37                    frau   445
38                   femme   445
39                    sexy   445
40                   jolie   445
41                   girls   445
42                  people   445
43                   belle   445
44                 popular   445
45                  ladies   445
46                    lady   445
47                  femmes   445
48                   women   445
49                   donna   445

No popular car in 2012

In [105]:
tagFreq(geneva_salon_data[geneva_salon_data['year']=='2013'])[59:]

/home/nevena/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:19: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

                                        word  freq
59                                 worldcars    58
60                                         g    57
61                                       amg    50
62                                  mercedes    48
63                                      benz    48
64                                         b    48
65                                         s    43
66                                       rot    34
67                                        rs    33
68                                         w    33
69                                        mb    32
70                                       bmw    31
71                                     sport    31
72                                   porsche    30
73                                         t    29
74                                        gt    26
75                                       red    26
76                                         r    26
77                                     white    24
78                                    bayern    22
79                                         f    22
80                                      ompi    21
81                                      wipo    21
82                                   palexpo    21
83   saloninternationaldesinventionsdegenève    21
84                      genevainventionsfair    21
85                                      weis    18
86                                  gemballa    18
87                                  inventor    18
88                                     weiss    18
..                                       ...   ...
397                                    70200     1
398                                      art     1
399                                  lenkrad     1
400                                b6concept     1
401                                       tl     1
402                                headlight     1
403                               wolkswagen     1
404                                      c41     1
405                                       ef     1
406                                  romania     1
407                                      632     1
408                                      rb9     1
409                                 isolated     1
410                                 pro160ns     1
411                                       p4     1
412                                    innen     1
413                              granturismo     1
414                                     tyre     1
415                                    green     1
416                                    front     1
417                               mcstradale     1
418                                  bertone     1
419                                  tunning     1
420                                   tekart     1
421                                perceptol     1
422                                   inside     1
423                                  concept     1
424                                   turkey     1
425                                     renn     1
426                                      man     1

[368 rows x 2 columns]

Mercedes in 2013

In [106]:
tagFreq(geneva_salon_data[geneva_salon_data['year']=='2014'])[0:50]

/home/nevena/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:19: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

                            word  freq
0                         geneva  1530
1                           show  1516
2                          motor  1490
3                  international  1490
4                           84th  1490
5                           2014  1117
6                        concept   329
7                           mans   206
8                      endurance   206
9                         racing   188
10                 lemanslegends   177
11                        heures   177
12  genevainternationalmotorshow   177
13                            24   177
14                            du   177
15               genevamotorshow   151
16                   anthonygurr   149
17                           car    84
18                     crossover    75
19                        design    74
20                        pagani    69
21                       hyundai    54
22                        hybrid    48
23                          cell    46
24                       intrado    46
25                         coupe    46
26                          fuel    46
27                        geneve    43
28                          cars    43
29                     prototype    41
30                        genève    39
31                            5d    38
32               canoneos5dmkiii    38
33                   rafdebruyne    38
34                     5dmarkiii    38
35                         mark3    38
36                       5dmkiii    38
37                           eos    38
38                         canon    38
39                   debruyneraf    38
40                 canoneos5dmk3    38
41                           mk3    38
42               canoneos5dmkill    38
43        debruynerafphotography    38
44                       carshow    37
45                          genf    37
46                         zonda    35
47                    revolucion    35
48                   lamborghini    34
49                        huayra    33

Le mans legends in 2014 (didn't even know that this is a car)

In [109]:
tagFreq(geneva_salon_data[geneva_salon_data['year']=='2015'])[59:]

/home/nevena/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:19: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

                                   word  freq
59                                 cute    80
60                                woman    80
61                                   df    70
62                                coupé    49
63                            prototype    49
64                           conceptcar    49
65                                  awd    38
66                                  4wd    38
67                                  4x4    38
68                          lamborghini    29
69                           exhibition    24
70                           exposition    24
71                                 expo    24
72                              offroad    23
73                                  suv    23
74                            worldcars    23
75                                 cars    23
76                                sport    23
77                  genevamotorshow2015    22
78                            crossover    22
79                              carshow    21
80                              mclaren    21
81                                 audi    21
82                                   ze    20
83                         zeroemission    20
84                                 sony    19
85         internationalerautosalongenf    19
86                                rx100    19
87   saloninternationaldel’autodegenève    19
88                      canoneos5dmkill    18
..                                  ...   ...
582                              touran     1
583                             radical     1
584                                2008     1
585                            rinspeed     1
586                          douglasc47     1
587                          rangerover     1
588                                 rct     1
589                            borgward     1
590                                 dbx     1
591                           fabdesign     1
592                            slklasse     1
593                                 swb     1
594                             lafinal     1
595                               zonda     1
596                      rufturboflorio     1
597                          mitsubishi     1
598                                back     1
599                               jante     1
600                            3wheeler     1
601                               macan     1
602                           supercars     1
603                           taillight     1
604                               skoda     1
605                                 mtm     1
606                                7004     1
607                                 f12     1
608                                camo     1
609                             qashqai     1
610                               elise     1
611                                 dkr     1

[553 rows x 2 columns]

Lamborghini in 2015

In [110]:
tagFreq(geneva_salon_data[geneva_salon_data['year']=='2016'])

/home/nevena/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:19: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

                  word  freq
0                 2016   135
1            motorshow   111
2               racing   109
3            exclusive   108
4             supercar   108
5        international   108
6                  car   108
7                retro   107
8               geneve   107
9                 auto   107
10          conceptcar   106
11       rassemblement   106
12             classic   106
13             vintage   106
14             concept   106
15          vintagecar   106
16          classiccar   106
17                gims   101
18              geneva    32
19               motor    30
20                show    29
21             renault    14
22             porsche    14
23           chevrolet    12
24          koenigsegg    11
25            corvette    11
26             peugeot    10
27               dakar     9
28                 gt3     9
29                  rs     8
..                 ...   ...
207            miniwrc     1
208         308rhybrid     1
209        carbonfiber     1
210        mclaren650s     1
211             carbon     1
212               gt86     1
213       discovolante     1
214               308r     1
215  chevroletcorvette     1
216               2015     1
217               hemi     1
218                new     1
219              d5200     1
220              675lt     1
221              d5300     1
222              lusso     1
223             regera     1
224                gtr     1
225                 p1     1
226          supercars     1
227              tuner     1
228          subaruwrx     1
229        huracanavio     1
230                gte     1
231          gtconcept     1
232            brabham     1
233            650sgtr     1
234            citroen     1
235               blue     1
236              r8v10     1

[237 rows x 2 columns]

Some vintage car in 2016

### Let's see some pictures

In [21]:
urls=[getUrlForTags("motorshow",46.168,6.119,2005,-1)[0]['url_m'],
      getUrlForTags("motorshow",46.235,6.119,2006,-1)[1]['url_m'],
      getUrlForTags("motorshow",46.235,6.119,2007,-1)[1]['url_m'],
      getUrlForTags("motorshow",46.235,6.119,2008,-1)[2]['url_m'],
      getUrlForTags("motorshow",46.168,6.119,2009,-1)[1]['url_m'],
      getUrlForTags("motorshow",46.168,6.119,2010,-1)[2]['url_m'],
      getUrlForTags("motorshow",46.168,6.119,2011,-1)[4]['url_m'],
      getUrlForTags("motorshow",46.168,6.119,2012,-1)[0]['url_m'],
      getUrlForTags("motorshow",46.168,6.119,2013,-1)[6]['url_m'],
      getUrlForTags("motorshow",46.168,6.119,2014,-1)[23]['url_m'],
      getUrlForTags("motorshow",46.168,6.119,2015,-1)[14]['url_m'],
      getUrlForTags("motorshow",46.168,6.119,2016,-1)[6]['url_m']
    ]

In [202]:
#save these images just in case
import urllib.request
for i in urls:
    urllib.request.urlretrieve(i, str(i.index)+".jpg")

In [22]:
df_genev=geneva_salon_data[['year','userid']].groupby('year').count().reset_index()

In [23]:
import matplotlib.pyplot as plt
import numpy as np

from matplotlib.patches import Circle
from matplotlib.offsetbox import (TextArea, DrawingArea, OffsetImage,
                                  AnnotationBbox)
from matplotlib.cbook import get_sample_data
from skimage import io

fig, ax = plt.subplots()
fig.suptitle('Popular cars in Geneva Car Salon', fontsize=14)
ax.bar(df_genev.year.astype(int),df_genev.userid,picker=True,color='lightsalmon')

def onpick3(event):   
    artist = event.artist
     
    i=int(event.artist.get_x())
    xy=[i,df_genev[df_genev.year==str(i)]['userid']]
  
    a = io.imread(urls[i-2005],format='png')

    imagebox = OffsetImage(a, zoom=0.7)
    imagebox.image.axes = ax
    normalize=[0,0]
    if((i==2011) | (i==2014)): normalize=[-200,-150]
    ab = AnnotationBbox(imagebox, xy,
                        xybox=(100+normalize[0],150+normalize[1]),
                        xycoords='data',
                        boxcoords="offset points",
                        pad=0.3,
                        arrowprops=dict(arrowstyle="->"))
    ax.add_artist(ab)
    event.canvas.draw()
    ab.remove()
        
fig.canvas.mpl_connect('pick_event', onpick3)
plt.show()
plt.savefig('geneva_bars.png')

# Popular places by number of users

In [24]:
most_users=rounded_geo.groupby(["lat","lon","year","userid"]).count()

In [25]:
user_per_loc=most_users.reset_index().groupby(['lat','lon','year'])['userid'].nunique()

In [26]:
users_per_loc=pd.DataFrame(user_per_loc).sort('userid',ascending=False).reset_index()

/home/nevena/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

In [27]:
df=pd.DataFrame(index=range(2005,2017),columns=['lat','lon','userid'])
for x in range(2005,2017):
    max_num=max(users_per_loc[users_per_loc['year']==str(x)]['userid'])
    data=users_per_loc[(users_per_loc['year']==str(x)) & (users_per_loc['userid']==max_num)]
    df.set_value(x, 'lat', data['lat'].values[0])
    df.set_value(x, 'lon', data['lon'].values[0])
    df.set_value(x, 'userid', data['userid'].values[0])

Most popular place is 47.377 8.54 almost in all years. Let's see what it is

In [32]:
data_most_pop=rounded_geo[(rounded_geo.lat==47.377) & (rounded_geo.lon==8.54)]
df=pd.DataFrame(columns=['year','word','freq'])
for year in range(2005,2017):
    #print(tagFreq(data_most_pop[data_most_pop.year==str(year)])[:21])
    df=df.append(pd.DataFrame(tagFreq(data_most_pop[data_most_pop.year==str(year)],year)),ignore_index=True)

/home/nevena/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:19: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

In [33]:
pop_tags_for_pop_location_per_year=df[(df.word!="zurich") & (df.word!="zürich")& (df.word!="swiss")& (df.word!="schweiz")
   & (df.word!="suisse")& (df.word!="switzerland") & (df.word!="svizzera") & (df.freq>5)].set_index(["year","freq"])
pop_tags_for_pop_location_per_year

                                word
year   freq
2005.0 14.0           bahnhofstrasse
       13.0                    k750i
       13.0                 shopping
       13.0                    daily
       13.0                 camphone
       13.0                christmas
       9.0                    lugano
       9.0                      chur
       9.0                bellinzona
       8.0                  downtown
       7.0                 buildings
       6.0                     river
2006.0 22.0  geo:country=switzerland
       22.0          geo:city=zurich
       16.0                     food
       15.0                     city
       11.0             hauptbahnhof
       9.0                       sbb
       9.0                       vbz
       8.0                     train
       8.0                trammuseum
       7.0                     toniv
       7.0               mainstation
       7.0                    europe
       7.0                    ©toniv
       7.0                       d50
       6.0                      2006
2007.0 31.0              freestylech
       29.0                      vbz
       26.0               trammuseum
...                              ...
2015.0 9.0              squareformat
       9.0     uploaded:by=instagram
       9.0              instagramapp
       9.0                    square
       9.0             iphoneography
       8.0                      2015
       8.0                        bw
       8.0                     white
       7.0                     black
       6.0                      tram
       6.0                    winter
2016.0 12.0                       bw
       11.0                   europe
       11.0            blackandwhite
       11.0                   street
       10.0                    urban
       10.0        streetphotography
       9.0          urbanexploration
       9.0                       bnw
       9.0             ivanrigamonti
       8.0                        ch
       8.0                      2016
       8.0                       man
       7.0            bahnhofstrasse
       7.0                    flickr
       7.0                     500px
       6.0                 backlight
       6.0         zurichmainstation
       6.0                    people
       6.0                monochrome

[1219 rows x 1 columns]

In [ ]:
#To print and manually choose pictures
#year='XXXX'
#severalPhotos=getUrlForTags("bahnhofstrasse",47.377,8.54,year,-1)
#for i in severalPhotos:
    #print(i['url_m'])

In [35]:
df=users_per_loc[(users_per_loc.lat==47.377) & (users_per_loc.lon==8.54)][['year','userid']]
urls=[getUrlForTags("bahnhofstrasse",47.377,8.54,2005,-1)[0]['url_m'],
        getUrlForTags("bahnhofstrasse",47.377,8.54,2006,-1)[5]['url_m'],
        getUrlForTags("bahnhofstrasse",47.377,8.54,2007,-1)[2]['url_m'],
        getUrlForTags("bahnhofstrasse",47.377,8.54,2008,-1)[9]['url_m'],
        getUrlForTags("bahnhofstrasse",47.377,8.54,2009,-1)[4]['url_m'],
        getUrlForTags("bahnhofstrasse",47.377,8.54,2010,-1)[2]['url_m'],
        getUrlForTags("bahnhofstrasse",47.377,8.54,2011,-1)[0]['url_m'],
        getUrlForTags("bahnhofstrasse",47.377,8.54,2012,-1)[0]['url_m'],
        getUrlForTags("bahnhofstrasse",47.377,8.54,2013,-1)[1]['url_m'],
        getUrlForTags("bahnhofstrasse",47.377,8.54,2014,-1)[9]['url_m'],
        getUrlForTags("bahnhofstrasse",47.377,8.54,2015,-1)[5]['url_m'],
        getUrlForTags("bahnhofstrasse",47.377,8.54,2016,-1)[54]['url_m']]

In [210]:
#save images just in case
for i in urls:
    urllib.request.urlretrieve(i, str(i.index)+"zurich.jpg")

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

from matplotlib.patches import Circle
from matplotlib.offsetbox import (TextArea, DrawingArea, OffsetImage,
                                  AnnotationBbox)
from matplotlib.cbook import get_sample_data
from skimage import io

fig, ax = plt.subplots()
fig.suptitle('Zurich train station over time\nClick on the bar to display a picture', fontsize=14)
ax.bar(df.year.astype(int),df.userid,picker=True,color='lightsalmon')

def onpick3(event):   
    artist = event.artist
     
    i=int(event.artist.get_x())
    xy=[i,df[df.year==str(i)]['userid']]
  
    a = io.imread(urls[i-2005],format='png')

    imagebox = OffsetImage(a, zoom=0.7)
    imagebox.image.axes = ax
    normalize=[0,0]
    if((i>2009) & (i<2014)): normalize=[-200,-150]
    ab = AnnotationBbox(imagebox, xy,
                        xybox=(100+normalize[0],150+normalize[1]),
                        xycoords='data',
                        boxcoords="offset points",
                        pad=0.3,
                        arrowprops=dict(arrowstyle="->"))
    ax.add_artist(ab)
    event.canvas.draw()
    ab.remove()
        
fig.canvas.mpl_connect('pick_event', onpick3)
plt.show()

# Number of posts per month, daytime

In [1]:
import datetime

In [10]:
newdf=rounded_geo
newdf['time']=newdf['datetaken'].map(lambda x: datetime.datetime.strptime(x[11:],'%H:%M:%S').time())
newdf

,userid,title,dateupload,datetaken,views,tags,lat,lon,place_id,woeid,year,month,time
50258,8291917@N07,Cable car to Isérables,1206126905,2005-01-01 03:29:29,826,vineyard cablecar wallis rhone kabelbaan ridde...,46.165,7.240,B4wAWYtWWrh4G1M,782850.0,2005,01,03:29:29
50259,71144572@N00,Volkswagen Transporter in Wettingen 1971 001,1199648928,2005-01-01 03:00:00,1451,vw volkswagen transporter archiv0001,47.472,8.324,y2rhZ5BTW7ltcr39fQ,29397634.0,2005,01,03:00:00
50260,12644939@N02,Versoix on ice,1196271836,2005-01-01 00:00:00,24490,blue trees winter light sky sun white lake col...,46.277,6.170,asoDs99WWrhR4p8,782999.0,2005,01,00:00:00
50261,12644939@N02,Versoix Peer On Ice,1194803060,2005-01-01 00:00:00,1706,winter lake ice water switzerland suisse genev...,46.278,6.170,hx8k.dhWWr7TWXk,784567.0,2005,01,00:00:00
50262,71144572@N00,Poschiavo Schweiz,1241178554,2005-01-01 04:01:46,333,schweiz switzerland 1987 graubünden poschiavo ...,46.325,10.057,d2mlVahWWrkxTxQ,783762.0,2005,01,04:01:46
50263,71144572@N00,Poschiavo Schweiz,1241178523,2005-01-01 04:01:41,392,schweiz switzerland 1987 graubünden poschiavo ...,46.325,10.057,d2mlVahWWrkxTxQ,783762.0,2005,01,04:01:41
50264,71144572@N00,Hochwasser Poschiavo Schweiz,1241178513,2005-01-01 04:01:40,543,schweiz switzerland 1987 hochwasser graubünden...,46.325,10.057,d2mlVahWWrkxTxQ,783762.0,2005,01,04:01:40
50265,71144572@N00,Poschiavo Schweiz,1241178502,2005-01-01 04:01:39,411,schweiz switzerland 1987 graubünden poschiavo ...,46.325,10.057,d2mlVahWWrkxTxQ,783762.0,2005,01,04:01:39
50266,71144572@N00,Soglio Schweiz,1241178489,2005-01-01 04:01:07,372,schweiz switzerland 1986 graubünden soglio arc...,46.341,9.536,BcxKUdRWWr5UwuQ,784209.0,2005,01,04:01:07
50267,71144572@N00,Löbbia Bergell Schweiz,1241178407,2005-01-01 04:01:14,450,schweiz switzerland 1986 graubünden bergell ar...,46.376,9.658,YOtIRpJWWrmy9lk,783173.0,2005,01,04:01:14
50268,71144572@N00,Castasegna Schweiz,1241178404,2005-01-01 04:00:26,335,schweiz switzerland 1986 graubünden castasegna...,46.333,9.511,0IcztHJWWrgBQl0,782026.0,2005,01,04:00:26
50269,71144572@N00,Castasegna Schweiz,1241178399,2005-01-01 04:01:09,334,schweiz switzerland 1986 graubünden castasegna...,46.333,9.511,0IcztHJWWrgBQl0,782026.0,2005,01,04:01:09
50270,71144572@N00,St.Moritz Schweiz,1241178395,2005-01-01 04:01:16,506,schweiz switzerland 1986 stmoritz graubünden a...,46.497,9.837,yhBCEb1WWr5tiu8,784032.0,2005,01,04:01:16
50271,71144572@N00,Surava bei Tiefenkastel Schweiz,1241178345,2005-01-01 04:01:37,360,schweiz switzerland 1985 graubünden surava arc...,46.666,9.613,Ptq.YW5WWr41hcU,784348.0,2005,01,04:01:37
50272,71144572@N00,Chur Schweiz,1241178341,2005-01-01 04:01:23,329,schweiz switzerland brunnen chur 1985 graubünd...,46.848,9.529,2qZ5lVlWWriifcM,782105.0,2005,01,04:01:23
50273,71144572@N00,Chur Schweiz,1241178337,2005-01-01 04:01:24,427,schweiz switzerland chur 1985 graubünden archi...,46.848,9.529,2qZ5lVlWWriifcM,782105.0,2005,01,04:01:24
50274,71144572@N00,Chur Schweiz,1241178333,2005-01-01 04:01:25,371,schweiz switzerland chur 1985 graubünden archi...,46.848,9.529,2qZ5lVlWWriifcM,782105.0,2005,01,04:01:25
50275,71144572@N00,Alvaneu Schweiz,1241178329,2005-01-01 04:01:27,352,schweiz switzerland 1985 graubünden alvaneu ar...,46.678,9.643,3Rz5MRJWWrtceQ8,781611.0,2005,01,04:01:27
50276,71144572@N00,Alvaneu Schweiz,1241178324,2005-01-01 04:01:26,353,schweiz switzerland 1985 graubünden alvaneu ar...,46.678,9.643,3Rz5MRJWWrtceQ8,781611.0,2005,01,04:01:26
50277,71144572@N00,Soglio Schweiz,1241178320,2005-01-01 04:01:28,416,schweiz switzerland 1985 graubünden soglio arc...,46.341,9.536,BcxKUdRWWr5UwuQ,784209.0,2005,01,04:01:28
50278,71144572@N00,Soglio Schweiz,1241178316,2005-01-01 04:01:29,369,schweiz switzerland 1985 graubünden soglio arc...,46.341,9.536,BcxKUdRWWr5UwuQ,784209.0,2005,01,04:01:29
50279,71144572@N00,Castasegna ital.Schweiz,1241178311,2005-01-01 04:01:48,622,schweiz switzerland border mazda 1985 customs ...,46.333,9.511,0IcztHJWWrgBQl0,782026.0,2005,01,04:01:48
50280,71144572@N00,Borgonovo im Bergell Schweiz,1241178308,2005-01-01 04:00:03,376,schweiz switzerland 1985 bergell borgonovo arc...,46.344,9.612,24C2LGBWWrtc2SA,781872.0,2005,01,04:00:03
50281,71144572@N00,Soglio Bergell Schweiz,1240728399,2005-01-01 04:01:33,463,schweiz switzerland 1985 graubünden bergell so...,46.341,9.536,BcxKUdRWWr5UwuQ,784209.0,2005,01,04:01:33
50282,71144572@N00,Soglio Bergell Schweiz,1240728396,2005-01-01 04:01:34,600,schweiz switzerland 1985 graubünden bergell so...,46.341,9.536,BcxKUdRWWr5UwuQ,784209.0,2005,01,04:01:34
50283,71144572@N00,Klosters Schweiz,1240726785,2005-01-01 04:00:20,367,schweiz switzerland 1985 klosters graubünden a...,46.879,9.880,wkMgi35WWrhbKWw,782925.0,2005,01,04:00:20
50284,71144572@N00,Filisur Schweiz,1240726779,2005-01-01 04:00:21,366,schweiz switzerland 1985 graubünden filisur ar...,46.673,9.685,MMbrB9JWWrgyB5A,782444.0,2005,01,04:00:21
50285,71144572@N00,Schuls Schweiz,1240726776,2005-01-01 04:00:19,320,schweiz switzerland 1984 graubünden schuls arc...,46.797,10.300,2ftjI81WWr4Odsc,784142.0,2005,01,04:00:19
50286,71144572@N00,Schuls Schweiz,1240726771,2005-01-01 04:00:18,292,window schweiz switzerland fenster 1984 graubü...,46.797,10.300,2ftjI81WWr4Odsc,784142.0,2005,01,04:00:18
50287,71144572@N00,Schuls Schweiz,1240726767,2005-01-01 04:00:20,317,schweiz switzerland 1984 graubünden schuls arc...,46.797,10.300,2ftjI81WWr4Odsc,784142.0,2005,01,04:00:20
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2839798,132731801@N02,DSC01974,1483361383,2016-12-31 15:55:52,7,NaN,47.525,7.711,.kBPI3xQUL9PEzljKw,12593163.0,2016,12,15:55:52
2839799,132731801@N02,DSC01973,1483361383,2016-12-31 15:55:16,6,NaN,47.526,7.711,.kBPI3xQUL9PEzljKw,12593163.0,2016,12,15:55:16
2839800,132731801@N02,DSC01979,1483361384,2016-12-31 15:59:23,6,NaN,47.525,7.711,.kBPI3xQUL9PEzljKw,12593163.0,2016,12,15:59:23
2839801,132731801@N02,DSC01981,1483361385,2016-12-31 16:00:47,5,NaN,47.525,7.711,.kBPI3xQUL9PEzljKw,12593163.0,2016,12,16:00:47
2839802,132731801@N02,DSC01982,1483361386,2016-12-31 16:01:26,5,NaN,47.525,7.711,.kBPI3xQUL9PEzljKw,12593163.0,2016,12,16:01:26
2839803,132731801@N02,DSC01922,1483361348,2016-12-31 15:17:11,5,NaN,47.525,7.711,.kBPI3xQUL9PEzljKw,12593163.0,2016,12,15:17:11
2839804,132731801@N02,DSC01937,1483361358,2016-12-31 15:27:39,5,NaN,47.525,7.711,.kBPI3xQUL9PEzljKw,12593163.0,2016,12,15:27:39
2839805,132731801@N02,DSC01947,1483361365,2016-12-31 15:35:38,5,NaN,47.526,7.711,.kBPI3xQUL9PEzljKw,12593163.0,2016,12,15:35:38
2839806,132731801@N02,DSC01955,1483361371,2016-12-31 15:41:33,6,NaN,47.525,7.711,.kBPI3xQUL9PEzljKw,12593163.0,2016,12,15:41:33
2839807,132731801@N02,DSC01959,1483361374,2016-12-31 15:44:23,6,NaN,47.525,7.711,.kBPI3xQUL9PEzljKw,12593163.0,2016,12,15:44:23
2839808,132731801@N02,DSC01962,1483361376,2016-12-31 15:46:25,6,NaN,47.525,7.711,.kBPI3xQUL9PEzljKw,12593163.0,2016,12,15:46:25
2839809,132731801@N02,DSC01980,1483361385,2016-12-31 16:00:32,5,NaN,47.525,7.711,.kBPI3xQUL9PEzljKw,12593163.0,2016,12,16:00:32
2839810,112834105@N04,DSC00855 (2),1483355652,2016-12-31 11:47:39,4,NaN,46.728,7.711,ksrJxSFWWr.HKOQ,785296.0,2016,12,11:47:39
2839811,112834105@N04,DSC00865 (2),1483355653,2016-12-31 11:53:15,4,NaN,46.726,7.710,DCC3Wf5QV7rEcqBwSA,15001171.0,2016,12,11:53:15
2839812,112834105@N04,DSC00869 (2),1483355653,2016-12-31 11:55:52,4,NaN,46.726,7.711,DCC3Wf5QV7rEcqBwSA,15001171.0,2016,12,11:55:52
2839813,112834105@N04,DSC00872 (2),1483355654,2016-12-31 11:58:11,4,NaN,46.727,7.711,DCC3Wf5QV7rEcqBwSA,15001171.0,2016,12,11:58:11
2839814,112834105@N04,DSC00924 (2),1483355659,2016-12-31 13:01:33,4,NaN,46.747,7.682,VFfv2GZQUL_AeLQWKw,12593111.0,2016,12,13:01:33
2839815,112834105@N04,DSC00926 (2),1483355659,2016-12-31 13:02:36,4,NaN,46.747,7.682,VFfv2GZQUL_AeLQWKw,12593111.0,2016,12,13:02:36
2839816,28582697@N07,Silvester 2016 Nachlese,1483347185,2016-12-31 17:30:39,100,NaN,47.074,7.706,xTWt5h1UVL95.XnqZQ,56558118.0,2016,12,17:30:39
2839817,28582697@N07,Silvester 2016 Nachlese,1483347186,2016-12-31 17:28:44,228,NaN,47.074,7.706,xTWt5h1UVL95.XnqZQ,56558118.0,2016,12,17:28:44
2839827,77953579@N08,Givre luisant,1483309206,2016-12-31 15:03:00,27,lausanne vaud suisse ch,46.560,6.681,QtsTB8RWWrgwYBY,782348.0,2016,12,15:03:00
2839828,28875606@N08,ViaJura Regio 57 La Caquerelle,1483280726,2016-12-31 08:45:31,2,NaN,47.381,7.213,C4BOpJ5QUL8e4rJPiw,12593133.0,2016,12,08:45:31
2839829,28875606@N08,ViaJura Regio 58,1483280727,2016-12-31 09:32:41,2,NaN,47.370,7.227,pcmyVN1QUL_YpkMTuA,12593196.0,2016,12,09:32:41
2839830,28875606@N08,ViaJura Regio 59 Cras de Fonnes,1483280727,2016-12-31 09:48:18,2,NaN,47.370,7.230,pcmyVN1QUL_YpkMTuA,12593196.0,2016,12,09:48:18
2839831,28875606@N08,ViaJura Regio 60 Les Lavoirs,1483280728,2016-12-31 10:08:19,2,NaN,47.362,7.242,pcmyVN1QUL_YpkMTuA,12593196.0,2016,12,10:08:19
2839832,28875606@N08,ViaJura Regio 61,1483280729,2016-12-31 10:53:56,1,NaN,47.369,7.266,pcmyVN1QUL_YpkMTuA,12593196.0,2016,12,10:53:56
2839833,28875606@N08,ViaJura Regio 62,1483280729,2016-12-31 10:56:11,0,NaN,47.368,7.267,pcmyVN1QUL_YpkMTuA,12593196.0,2016,12,10:56:11
2839834,28875606@N08,ViaJura Regio 63,1483280730,2016-12-31 11:05:47,3,NaN,47.367,7.272,pcmyVN1QUL_YpkMTuA,12593196.0,2016,12,11:05:47
2839835,28875606@N08,ViaJura Regio 64,1483280730,2016-12-31 11:55:14,1,NaN,47.368,7.303,pcmyVN1QUL_YpkMTuA,12593196.0,2016,12,11:55:14
2839836,59740940@N06,meadow and frosty end,1483204994,2016-12-31 15:10:37,89,meadow frosty kalt frost wiese alm alp bremgar...,47.331,7.657,XSrI7StQUL8smfm5zg,12593102.0,2016,12,15:10:37

In [11]:
def daytime(x):
    noon= datetime.datetime(1900, 1, 2, 12, 0).time()
    morning=datetime.datetime(1900, 1, 2, 6, 0).time()
    eve=datetime.datetime(1900, 1, 2, 18, 0).time()
    midnight=datetime.datetime(1900, 1, 2, 23,59 ).time()
    if x<noon and x>morning:
        return "morning"
    elif x>noon and x<eve:
        return "afternoon"
    elif x>eve and x<midnight:
        return "evening"
    else:
        return "night"

In [12]:
newdf['daytime']=newdf['time'].map(lambda x: daytime(x))

In [13]:
newdf.groupby(['daytime']).count()[['userid']]

            userid
daytime
afternoon  1379243
evening     548584
morning     682812
night       178844

In [14]:
newdf['month']=newdf['datetaken'].map(lambda x: x[5:7])
perDayTime=newdf.groupby(['month','daytime']).count()[['userid']].reset_index()

In [22]:
perDayTime.pivot_table(index='month', columns='daytime', values='userid',
                aggfunc='sum', fill_value=0).plot.bar(stacked=True)

In [23]:
#plt.show()
plt.savefig("daytime.png")

# Word cloud per canton

In [3]:
import pickle
# this is to load from pickled data
with open('./df3.pickle', 'rb') as handle:
    cantons = pickle.load(handle)

In [4]:
loc_tags=newdf[['tags','lat','lon']]

In [5]:
loc_tags['location']= newdf.iloc[0:newdf.shape[0]-1, 6:8].apply(lambda x: str(x[0]) + ', ' + str(x[1]), axis=1)

/home/nevena/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [6]:
loc_tags=loc_tags[['tags','location']]

In [7]:
loc_tags=loc_tags.dropna()

In [8]:
frame=loc_tags.groupby('location')['tags'].sum()

In [9]:
tags_per_loc=pd.DataFrame(frame)

In [10]:
cantons_tags=cantons.set_index('location').join(tags_per_loc).reset_index()[['canton','tags']]

In [11]:
grouped_ca=cantons_tags.dropna().groupby('canton').sum()

In [12]:
only_swiss=grouped_ca.drop(['Auvergne-Rhône-Alpes','Baden-Württemberg','Bourgogne-Franche-Comté','Grand-Est','Hauts-de-France',
                'LOM','PIE','TAA','Tirol','VDA','VEN','Vorarlberg'])

In [13]:
only_swiss

                                                                               tags
canton
Aargau                            schweiz switzerland taxi zurich plymouth taxid...
Appenzell Ausserrhoden            train switzerland railway ag 17 sga treno appe...
Appenzell Innerrhoden             railroad switzerland railway ab trains railcar...
Basel-Landschaft                  tram basel strassenbahn bvb muttenz motorwagen...
Basel-Stadt                       theater tram basel strassenbahn bvb motorwagen...
Bern - Berne                      snowboardingcindy cat schweiz switzerland chat...
Fribourg - Freiburg               mob montbovon montreuxoberlandbernoisrailwaymo...
Genève                            lake love nature birds square switzerland swan...
Glarus                            switzerland flying 1998switzerland flying 1998...
Graubünden - Grigioni - Grischun  geotagged switzerland davos wef che 1990 world...
Jura                              bw schwarzweiss allthebest supershot flickrsbe...
Luzern                            2 luzern verkehrsmuseumluzern tram neuchatel 5...
Neuchâtel                         switzerland tn neuchâtel trolleybus hess 133 1...
Nidwalden                         28 lse hergiswil luzernstansengelbergsuiza emi...
Obwalden                          switzerland nikon europa suisse suiza luzern l...
Sankt Gallen                      re44ii stgallen switzerland svizzera yashicafx...
Schaffhausen                      classre44i 10029 steinamrhein sbb schweizerisc...
Schwyz                            railroad switzerland dr railway trains svizzer...
Solothurn                         train switzerland eisenbahn railway steam tren...
Thurgau                           railroad switzerland railway trains svizzera b...
Ticino                            railroad switzerland ticino railway trains svi...
Uri                               railroad switzerland railway trains svizzera b...
Valais - Wallis                   winter january stluc valdanniviers fotoanalogi...
Vaud                              tl lausanne trolleybus 801 filobus obus vbz fb...
Zug                               railroad switzerland railway zug trains svizze...
Zürich                            railroad switzerland railway trains zürich svi...

In [16]:
from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt
from os import path
from scipy.misc import imread
from matplotlib import colors as mcolors
import six
import random
          
def color_f(word, font_size, position, orientation, random_state=None, **kwargs):
        if(count*10)<100:
            color_pal='rgb('+str(count*10)+'%%,'+str(int(100/(count+1)))+'%%,%d%%)'
        else:
            color_pal='rgb('+str(int(100/3*(count+1)))+'%%,'+str(count*3)+'%%,%d%%)'
        return color_pal % random.randint(0, 30)


exclude=['switzerland', 'schweiz', 'suisse', 'svizzera', 'svizra', 'suiza', ',europe','europe','geo',',geo', 'lon', 'lat', 
                   'img', 'ch', 're', 'jpg', 'dsc', 'che', 've', 'in', 'the', 'zrh','fr', 'the', 'for', 'mm', 'geolon', 
                   'geolat', 'swiss', 'swis', 'nikon','europa','photo','photographe','geotagged','analog','analogue','canon','fuji','fujifilm','film',
        'canton', 'kanton', 'city', 'ville', 'country', 'geneve', 'gva', 'town', 'd40', 'd700', 'd4', '400d', '8800f', '35mm', 'f28', 's6000fd', 's6500fd']
for word in exclude:
    STOPWORDS.add(word)
    
count=0
for name in only_swiss.index.values:
    mymask = imread("./cantons/maps/"+name+".png",flatten=True)
    wc = WordCloud(background_color='white', max_words=2000, mask=mymask,stopwords=STOPWORDS).generate(only_swiss.ix[name]['tags'])
    plt.imshow(wc.recolor(color_func=color_f,random_state=count))
    count=count+1
    plt.axis('off')
    plt.savefig('./clouds/'+name+'2.png', dpi=300,transparent=True)

/home/nevena/anaconda3/lib/python3.5/site-packages/wordcloud/wordcloud.py:286: UserWarning: mask image should be unsigned byte between 0 and 255. Got a float array
  warnings.warn("mask image should be unsigned byte between 0 and"

In [ ]:
from IPython.display import Image
from IPython.display import display
from IPython.display import HTML
from os import listdir
from os.path import isfile, join
onlyfiles = [f for f in listdir('./clouds/') if isfile(join('./clouds/', f))]
#ls=[]
#for fname in onlyfiles:
#    x= Image(filename=fname) 
#    ls.extend([x])
    
imagesList=''.join( ["<img style='width: 320px; margin: -30px; float: left;' src='%s' />" % str("./clouds/"+s) 
                 for s in onlyfiles ])
display(HTML(imagesList))

# Bubbles

In [3]:
def fill_nan(tag, title):
    '''we check first if the tag is null, to which case we fill it with its non-nan corrresponding title'''
    if((str(tag) == 'none') or (str(tag) == 'nan')):
        if((str(title) != 'none') and ( str(title) != 'nan')):
            return title
    else:
        #We append the title to the tags in order to, optimistically get more relevant informations
        if((str(title) != 'none') and ( str(title) != 'nan')):
            return tag + ' ' + title
        return tag

In [4]:
data=newdf

In [5]:
data.dropna(subset=['userid','tags'], how='all', inplace= True)

In [6]:
data['tags'] = data[['title', 'tags']] \
                        .apply(lambda x : fill_nan(str(x['tags']), str(x['title'])), axis=1)

In [8]:
#keep only the relevent columns
data = data[['userid', 'datetaken', 'views', 'tags', 'lat', 'lon']]
data =data.ix[1:]

In [93]:
#data1 = data.copy()

In [9]:
import re
def preprocessor(tags):
    
    if('=' in tags):
        m = re.search('(?<==).*', tags)
        tags = m.group(0)
    tags = re.sub('[^?a-zA-Z \n]', ' ', tags.lower())
    tags = re.sub(r'(  +|\n)', " ", tags) 
    tags = re.sub(r'(\?+)', "", tags) 
    remove_words =['switzerland', 'schweiz', 'suisse', 'svizzera', 'svizra', 'suiza', 'europe' 'geo', 'lon', 'lat', 
                   'img', 'ch', 're', 'jpg', 'dsc', 'che', 've', 'in', 'the', 'zrh','fr', 'the', 'for', 'mm', 'geolon', 
                   'geolat']
    tags = ' '.join([word for word in tags.split(' ') if ((not len(word) == 1) & (not word in remove_words))])
    tags = re.sub(r'(^(  ?)|(  ?)$)', '', tags)
    if (len(tags) == 0): return np.nan
    return tags

In [10]:
data['tags'] = data.tags.apply(lambda x: preprocessor(str(x)))

In [11]:
#credits to olga
import pickle
with open('./df3.pickle', 'rb') as handle:
    d = pickle.load(handle)

In [12]:
mapping = pd.DataFrame(d[['canton']])
mapping.index = d.location

In [13]:
cantonDict = mapping.to_dict()
cantonDict = cantonDict.get('canton')

In [14]:
abbr = dict([('Aargau', 'AG'), 
      ('Appenzell Ausserrhoden', 'AR'), 
      ('Appenzell Innerrhoden', 'AI'), 
      ('Basel-Landschaft', 'BL'), 
      ('Basel-Stadt', 'BS'), 
      ('Bern - Berne', 'BE'), 
      ('Fribourg - Freiburg', 'FR'), 
      ('Genève', 'GE'), 
      ('Glarus', 'GL'), 
      ('Graubünden - Grigioni - Grischun', 'GR'), 
      ('Jura', 'JU'), 
      ('Luzern', 'LU'), 
      ('Neuchâtel', 'NE'), 
      ('Nidwalden', 'NW'), 
      ('Obwalden', 'OW'), 
      ('Schaffhausen', 'SH'), 
      ('Schwyz', 'SZ'), 
      ('Solothurn', 'SO'), 
      ('Sankt Gallen', 'SG'), 
      ('Thurgau', 'TG'), 
      ('Ticino', 'TI'), 
      ('Uri', 'UR'), 
      ('Valais - Wallis', 'VS'), 
      ('Vaud', 'VD'), 
      ('Zug', 'ZG'), 
      ('Zürich', 'ZH')
     ])

In [15]:
def getAbbr(x):
    if abbr.get(x) is not None:
        return abbr.get(x)
    else:
        return 'other' #the ones not in Switzerland

In [16]:
def mapCanton(row):
    lat = row[0]
    lon = row[1]
    coordinate_long = str(lat)+", "+str(lon)
    x = cantonDict.get(coordinate_long)
    if x is not None:
        return getAbbr(x)
    else:
        lat = round(float(row[0]),3)
        lon = round(float(row[1]),3)
        coordinate_short = str(lat)+", "+str(lon)
        y = cantonDict.get(coordinate_short)
        if y is not None:
            return getAbbr(y)
        else:
            return y #we need y in order to see None

In [17]:
data['canton'] = 'none'
data['canton'] = data[['lat', 'lon']].apply(mapCanton, axis= 1)
data = data[(pd.notnull(data.canton))&(data.canton != 'other')]

In [18]:
data['year']= data['datetaken'].map(lambda x: x[:4])
data['month']= data['datetaken'].map(lambda x: x[5:7])

In [19]:
data['year'] = data.year.astype(int)
data['views'] = data.views.astype(int)
data['month'] = data.month.astype(int)
#data['lat']= round(data['lat'].astype(float),3)
#data['lon']= round(data['lon'].astype(float),3)
#drop rows whose both title and tags are null
data.dropna(subset=['tags'], how='any', inplace= True)
data = data.loc[(data.year > 2004) & (data.tags != "nan") & (data.tags != "none")]

In [20]:
data1 = data.copy()

In [21]:
data_co = data.groupby("canton")['userid'].count()
plt.style.use('ggplot')
_ = data_co.plot.pie(figsize=(10, 10))

In [23]:
top5_canton = data_co.to_frame()
top5_canton.sort(['userid'], ascending=[False], inplace=True)

/home/nevena/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:2: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from ipykernel import kernelapp as app

In [22]:
cantons = list(top5_canton.head(5).index.values.astype(str))
cantons

NameError: name 'top5_canton' is not defined

In [24]:
# credits to nevena functions

def word_count(str):
    counts = dict()
    words = str.split()

    for word in words:
        if word in counts:
            counts[word] += 1
        else:
            counts[word] = 1

    return counts

def tagFreq(dfm):   
    string='  '.join(dfm.dropna().tags.values)
    dictionary=word_count(string)
    dfWords=pd.DataFrame.from_dict(dictionary,orient='index')
    dfWords=dfWords.reset_index()
    dfWords=dfWords.rename(columns={'index': 'word', 0: 'freq'})
    dfWords=dfWords.sort(['freq'],ascending=False)
    dfWords = dfWords.reset_index()[['word','freq']]
    return dfWords

#get the top 10 tags
def top_10_tags(df):
    return df.head(15)


def preprocessor_2(tags):
    
    remove_words =['switzerland', 'schweiz', 'suisse', 'svizzera', 'svizra', 'suiza', 'europe' 'geo', 'lon', 'lat', 
                   'img', 'ch', 're', 'jpg', 'dsc', 'che', 've', 'in', 'the', 'zrh','fr', 'the', 'for', 'mm',
                   'europe', 'wallis', 'geolon', 'geolat', 'geneva', 'geneve', 'gen', 'genf', 'ginebra', 'ginevra', 'exif',
                   'gva', 'de', 'vaud', 'valais','vallis', 'zurich', 'rich', 'imag', 'europe', 'zuerich', 'zu', 'geo', 'zuerich',
                   'Bern', 'Berne', 'bern', 'berne' 'swiss']
    tags = ' '.join([word for word in tags.split(' ') if ((not len(word) < 3) & (not word in remove_words))])
    tags = re.sub(r'(^(  ?)|(  ?)$)', '', tags)
    if (len(tags) == 0): return np.nan
    return tags

In [25]:
#data = data1.copy()

In [26]:
df = pd.DataFrame(index=list(abbr.keys()), columns=np.arange(2005, 2017, 1))

In [27]:
data = data1.copy()

In [28]:
data['year']=data['datetaken'].map(lambda x: x[:4])

In [29]:
for canton in list(abbr.values()):
    for year in np.arange(2005, 2017, 1):
        top_10 = top_10_tags(tagFreq(data[(data.canton == canton) & (data.year == str(year))]))
        index = list(abbr.keys())[list(abbr.values()).index(canton)]
        df.ix[index, year] = preprocessor_2(' '.join(top_10.word.values))

/home/nevena/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:21: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

In [30]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
plt.style.use('ggplot')

import plotly as plotly
plotly.tools.set_credentials_file(username='nhallxd', api_key='218crnnLi3oOMTM9ICDV')
import plotly.plotly as py
import plotly.graph_objs as go

import pickle
%pylab inline
pylab.rcParams['figure.figsize'] = (10, 6) 
path = "./"
from subprocess import check_output
#print(check_output(["ls", data_path]).decode("utf8"))

from wordcloud import WordCloud, STOPWORDS

import warnings
warnings.filterwarnings("ignore")

Populating the interactive namespace from numpy and matplotlib

In [31]:
num_per_canton_year=data1.groupby(["canton","year"]).count()

In [32]:
num_per_canton_year=num_per_canton_year.reset_index()

In [33]:
only_per_canton=data1.groupby(["canton"]).count()

In [34]:
only_per_canton=only_per_canton.sort(["userid"],ascending=True).reset_index()

In [40]:
data=[]
for ab in list(abbr.values()):
    index = list(abbr.keys())[list(abbr.values()).index(str(ab))]
    val = list(df[df.index == index].values[0])
    sizes=num_per_canton_year[(num_per_canton_year['canton']==str(ab))]['userid']
    sizes=sizes.map(lambda x: x/50)
    y_value=only_per_canton[only_per_canton['canton']==str(ab)].index.tolist()[0]
    #print(list(map(lambda x: str(x) + '<br>', val)),"           end")
    trace0 = go.Scatter(
        x= df.columns.values,
        y= np.arange(10+(y_value*50), 23+(y_value*50), 1),
        text=list(map(lambda x: " ".join(x.split(" ")[:5]), val)),
        #list(map(lambda x: str(x.split(" ")[:5]), val))[0],
        name= index,
        mode='markers',
        marker=dict(
            size=sizes,
            sizemode='area'
        )
    )
    data.extend([trace0])
layout = go.Layout(
    autosize=False,
    width=1000,
    height=700,
    xaxis=dict(
        title='Year',
        titlefont=dict(
            family='Arial, sans-serif',
            size=18,
            color='nlack'
        ),
        showticklabels=True,
        tickangle=45,
        tickfont=dict(
            family='Old Standard TT, serif',
            size=14,
            color='black'
        ),
        exponentformat='e',
        showexponent='All'
    ),
    yaxis=dict(
        title='Popularity of a canton',
        titlefont=dict(
            family='Arial, sans-serif',
            size=18,
            color='black'
        ),
        showticklabels=True,
        tickangle=45,
        tickfont=dict(
            family='Old Standard TT, serif',
            size=14,
            color='black'
        ),
        exponentformat='e',
        showexponent='All'
    )
)
fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='Trend')

High five! You successfuly sent some data to your account on plotly. View your plot in your browser at https://plot.ly/~nhallxd/0 or inside your plot.ly account where it is named 'Trend'